max_vars(6).
max_body(6).

head_pred(loan_approved,1).

body_pred(very_young,1).
body_pred(young,1).
body_pred(middle_aged,1).
body_pred(senior,1).
body_pred(very_small_loan,1).
body_pred(small_loan,1).
body_pred(medium_loan,1).
body_pred(large_loan,1).
body_pred(very_large_loan,1).
body_pred(very_low_ratio,1).
body_pred(low_ratio,1).
body_pred(medium_ratio,1).
body_pred(high_ratio,1).
body_pred(very_high_ratio,1).
body_pred(very_high_interest,1).
body_pred(high_interest,1).
body_pred(medium_high_interest,1).
body_pred(medium_interest,1).
body_pred(low_interest,1).
body_pred(high_school,1).
body_pred(associate_degree,1).
body_pred(bachelor_degree,1).
body_pred(master_degree,1).
body_pred(doctorate,1).
body_pred(debt_consolidation,1).
body_pred(education_loan,1).
body_pred(medical_loan,1).
body_pred(personal_loan,1).
body_pred(venture_capital,1).
body_pred(home_improvement,1).
body_pred(male,1).
body_pred(female,1).
body_pred(has_default,1).
body_pred(no_default,1).
body_pred(renter,1).
body_pred(owner,1).
body_pred(high_risk,1).
body_pred(low_risk,1).
